const lang = {
    en: {
        search: "Search",
        placeholder: "What would you like to search ?",
        signout: "Sign out",
        home: "Home",
        gpt: "GPT-Search",
        nowPlaying: "Now Playing",
        popular: "Popular",
        topRated: "Top Rated",
        upComing: "UpComing",
    },
    hi: {
        search: "खोज",
        placeholder: "आप क्या खोजना चाहेंगे?",
        signout: "साइन आउट",
        home: "मुखपृष्ठ",
        gpt: "जीपीटी-खोज",
        nowPlaying: "अब खेल रहे हैं",
        popular: "लोकप्रिय",
        topRated: "टॉप रेटेड",
        upComing: "आगामी",
    },
    sp: {
        search: "buscar",
        placeholder: "¿Qué te gustaría buscar?",
        signout: "desconectar",
        home: "Página principal",
        gpt: "Búsqueda GPT",
        nowPlaying: "Jugando ahora",
        popular: "Popular",
        topRated: "Los más valorados",
        upComing: "próximo",
    },
    ja: {
        search: "検索",
        placeholder: "何を検索したいですか?",
        signout: "サインアウト",
        home: "ホームページ",
        gpt: "GPT サーチ",
        nowPlaying: "再生中",
        popular: "人気のある",
        topRated: "トップレート",
        upComing: "今後の",
    },
    ta: {
        search: "தேடல்",
        placeholder: "நீங்கள் எதைத் தேட விரும்புகிறீர்கள்?",
        signout: "வெளியேறு",
        home: "முகப்புப்பக்கம்",
        gpt: "GPT-தேடல்",
        nowPlaying: "தற்பொழுது ஓடிக்கொண்டிருக்கிறது",
        popular: "பிரபலமான",
        topRated: "சிறந்த தரமதிப்பீடு",
        upComing: "சிறந்த தரமதிப்பீடு",
    },
}

export default lang;